name: ml-env
channels:
  - defaults
dependencies:
  - python=3.11.11
  - pip
  - ipykernel
  - pip:
      - tensorflow==2.14.0
      - xgboost==3.0.0
      - scikit-learn==1.6.1
      - pytorch-lightning==2.5.1
      - scikeras==0.12.0
      - imbalanced-learn==0.12.3
      - imblearn==0.0
      - numpy==2.1.1
      - pandas==2.2.3
      - scipy==1.15.2
      - statsmodels==0.14.4
      - matplotlib==3.10.0
      - seaborn==0.13.2
      - opencv-python==4.11.0.86
      - albumentations==2.0.5
      - librosa==0.11.0
      - audioread==3.0.1
      - soundfile==0.13.1
      - ultralytics==8.3.111
      - thop==0.1.1.post2209072238
      - deep-sort-realtime==1.3.2
      - labelImg==1.8.6
      - tqdm==4.67.1
